quarkus.rest.path=/api

quarkus.management.enabled=true

#quarkus.cyclonedx.embedded.enabled=true
#quarkus.cyclonedx.embedded.compress=false

quarkus.cyclonedx.endpoint.enabled=true

quarkus.package.jar.tree-shake.mode=classes
