<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.y</groupId>
  <artifactId>product-y</artifactId>
  <version>1.0</version>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <cyclonedx.version>2.9.0</cyclonedx.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.a</groupId>
      <artifactId>lib-a</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>org.b</groupId>
      <artifactId>lib-b</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>org.c</groupId>
      <artifactId>lib-c</artifactId>
      <version>1.0</version>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.cyclonedx</groupId>
          <artifactId>cyclonedx-maven-plugin</artifactId>
          <version>${cyclonedx.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
