<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.acme</groupId>
        <artifactId>acme-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>acme-app</artifactId>
    <name>Acme - Application</name>

    <dependencies>
    <!--
        <dependency>
            <groupId>org.acme</groupId>
            <artifactId>quarkus-red</artifactId>
        </dependency>
        -->
        <dependency>
            <groupId>org.acme</groupId>
            <artifactId>quarkus-blue</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                            <goal>native-image-agent</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!-- forceC2>false</forceC2 -->
                    <!--
                    <modules>
                        <module>java.management</module>
                    </modules>
                    -->
                    <extensionJvmOptions>
                        <disableAll>false</disableAll>
                        <!--
                        <disableFor>
                            <extension>org.acme:quarkus-red</extension>
                        </disableFor>
                        -->
                    </extensionJvmOptions>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <properties>
                <skipITs>false</skipITs>
                <quarkus.native.enabled>true</quarkus.native.enabled>
            </properties>
        </profile>
    </profiles>
</project>
