/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.artifacts.Dependency;
import org.gradle.api.provider.ListProperty;

import java.util.Collection;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

/**
 * A simple 'hello world' plugin.
 */
public class PlaygroundPlugin implements Plugin<Project> {

    public void apply(Project project) {

        project.getConfigurations().register("greetingClasspath", config -> {
            final ListProperty<Dependency> dependencyListProp = project.getObjects().listProperty(Dependency.class);
            final AtomicReference<Collection<Dependency>> deps = new AtomicReference<>();
            final AtomicInteger callCount = new AtomicInteger();
            config.getDependencies().addAllLater(dependencyListProp.value(project.provider(() -> {
                System.out.println("Dependency provider call counter: " + callCount.incrementAndGet());
                var current = deps.get();
                if(current == null) {
                    current = List.of(project.getDependencies().create("xom:xom:1.3.9"));
                    deps.set(current);
                }
                return current;
            })));
            config.setTransitive(false);
        });
    }
}
