/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.artifacts.Dependency;
import org.gradle.api.artifacts.ResolvedArtifact;
import org.gradle.api.artifacts.ResolvedConfiguration;
import org.gradle.api.artifacts.ResolvedDependency;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.provider.ListProperty;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

/**
 * A simple 'hello world' plugin.
 */
public class PlaygroundPlugin implements Plugin<Project> {

    public void apply(Project project) {
        project.afterEvaluate(this::afterEvaluate);
    }

    private void afterEvaluate(Project project) {
        final Configuration testRuntimeCp = project.getConfigurations().getByName(JavaPlugin.TEST_RUNTIME_CLASSPATH_CONFIGURATION_NAME);

        System.out.println("Incoming artifacts:");
        testRuntimeCp.getIncoming().getArtifacts().forEach(a -> System.out.println("- " + a));

        System.out.println("Resolved artifacts:");
        ResolvedConfiguration resolvedConfig = testRuntimeCp.getResolvedConfiguration();
        resolvedConfig.getResolvedArtifacts().forEach(a -> System.out.println("- " + a));

        System.out.println("Module dependencies:");
        Set<String> collectedArtifacts = new HashSet<>();
        resolvedConfig.getFirstLevelModuleDependencies().forEach(d -> collectArtifacts(d, collectedArtifacts));
        for(String a : collectedArtifacts) {
            System.out.println("- " + a);
        }
    }

    private static void collectArtifacts(ResolvedDependency dep, Set<String> collectedArtifacts) {
        for(ResolvedArtifact a : dep.getModuleArtifacts()) {
            collectedArtifacts.add(toStringCoords(a));
        }
        for(ResolvedDependency child : dep.getChildren()) {
            collectArtifacts(child, collectedArtifacts);
        }
    }

    private static String toStringCoords(ResolvedArtifact a) {
        return a.getModuleVersion().getId().getGroup() + ":" + a.getModuleVersion().getId().getName() + ":" + a.getClassifier() + ":" + a.getExtension() + ":" + a.getModuleVersion().getId().getVersion();
    }
}
